server:
  servlet:
    context-path: /bank-issuer-service

spring:
  application:
    name: bank-issuer-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/card_bin_info}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

card-bin-service:
  bin-info-source-url: https://ecom-bininfo.s3.eu-west-1.amazonaws.com/bininfo.json.zip
  batch-size: 1000
  schedular:
    update-card-bin-info: 0 0 * * * *
